CREATE TABLE FellowshipCandidate (
  `ID` int NOT NULL,
  `CIC_ID` int NOT NULL,
  `LastName` varchar(255) NOT NULL,
  `MidddleName` varchar(255) NOT NULL,
  `FirstName` varchar(255) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `HiredCity` varchar(255) NOT NULL,
  `Degree` varchar(255) NOT NULL,
  `HiredDate` date DEFAULT NULL,
  `MobileNumber` varchar(255) NOT NULL,
  `PermanentPincode` varchar(255) NOT NULL,
  `HiredLab` varchar(255) NOT NULL,
  `Attitude` varchar(255) NOT NULL,
  `CommunicationRemark` varchar(255) NOT NULL,
  `KnowledgeRemark` varchar(255) NOT NULL,
  `AggregateRemarkUser_Details` varchar(255) NOT NULL,
  `CreatorStamp` datetime DEFAULT NULL,
  `CreatorUser` int DEFAULT NULL,
  `BirthDate` date DEFAULT NULL,
  `Is_Birth_Date_Verified` bit(1) DEFAULT NULL,
  `ParentName` varchar(255) DEFAULT NULL,
  `ParentOccupation` varchar(255) DEFAULT NULL,
  `ParentMobileNumber` varchar(255) DEFAULT NULL,
  `ParentsAnnualSalary` varchar(255) DEFAULT NULL,
  `LocalAddress` varchar(255) DEFAULT NULL,
  `PermanentAddress` varchar(255) DEFAULT NULL,
  `PhotoPath` varchar(255) DEFAULT NULL,
  `JoiningDate` date DEFAULT NULL,
  `CandidateStatus` bit(1) DEFAULT NULL,
  `PersonalInformation` varchar(255) DEFAULT NULL,
  `BankInformation` varchar(255) DEFAULT NULL,
  `EducationalInformation` varchar(255) DEFAULT NULL,
  `DocumentStatus` bit(1) DEFAULT NULL,
  `Remarks` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

